# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitHubCheckout@1
  displayName: 'Checkout Code'

- task: SFDXInstaller@1
  displayName: 'Install SFDX CLI'

- script: sfdx auth:jwt:grant --clientid $(SF_CLIENT_ID) --jwtkeyfile $(SF_JWT_KEY) --username $(SF_USERNAME) --instanceurl https://login.salesforce.com
  displayName: 'Authenticate with Salesforce'

- script: sfdx force:source:deploy -p force-app
  displayName: 'Deploy to Salesforce'
